import streamlit as st
import requests
import datetime
import json

# from exception.exceptions import TradingBotException
import sys

BASE_URL = "http://localhost:8500"  # Backend endpoint

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        payload = {"question": user_input}
        st.subheader("Execution Trace")
        trace_placeholder = st.empty()
        answer_placeholder = st.empty()
        save_placeholder = st.empty()
        trace_lines = []
        final_payload = None

        with st.spinner("Bot is thinking..."):
            response = requests.post(f"{BASE_URL}/query/stream", json=payload, stream=True)

            if response.status_code != 200:
                st.error(" Bot failed to respond: " + response.text)
            else:
                for line in response.iter_lines(decode_unicode=True):
                    if not line:
                        continue

                    event = json.loads(line)
                    event_type = event.get("type")
                    timestamp = event.get("timestamp", "")
                    message = event.get("message", "")
                    details = event.get("details", {})

                    if event_type == "final":
                        final_payload = details
                        continue

                    if event_type == "error":
                        st.error(" Bot failed to respond: " + message)
                        final_payload = None
                        break

                    detail_suffix = ""
                    if details:
                        detail_suffix = f" | {details}"
                    trace_lines.append(f"[{timestamp}] {event_type}: {message}{detail_suffix}")
                    trace_placeholder.code("\n".join(trace_lines), language="text")

        if final_payload:
            answer = final_payload.get("answer", "No answer returned.")
            saved_file = final_payload.get("saved_file")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')} 

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            answer_placeholder.markdown(markdown_content)
            if saved_file:
                save_placeholder.success(f"Saved to: {saved_file}")

    except Exception as e:
        st.error(f"The response failed due to {e}")
