import datetime
import logging
import os

logger = logging.getLogger(__name__)

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    os.makedirs(directory, exist_ok=True)
    
    
    # Create markdown content with metadata header
    markdown_content = f"""# 🌍 AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
    # **Created by:** Atriyo's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """
            
    try:
        # Write to markdown file with UTF-8 encoding
        # Generate timestamp-based filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        
        logger.info("Travel plan saved to %s", filename)
        return filename
        
    except Exception:
        logger.exception("Failed to save travel plan document")
        return None
